-- Arquivo gerado por scripts/generate-seed.ts — não edite à mão.
insert into game_private.characters (id, name, birth, country, gender, origin, century, area, weapon, aliases, weapon_aliases) values
  ('machado', 'Machado de Assis', '1839-06-21', 'Brasil', 'M', 'BR', 'XIX', 'Arte', 'Café', array['machado']::text[], '{}'::text[]),
  ('santos-dumont', 'Santos Dumont', '1873-07-20', 'Brasil', 'M', 'BR', 'XIX', 'Ciência', 'Pólen', array['dumont', 'santos dumont']::text[], '{}'::text[]),
  ('getulio', 'Getúlio Vargas', '1882-04-19', 'Brasil', 'M', 'BR', 'XIX', 'Política', 'Canela', array['getulio', 'vargas']::text[], '{}'::text[]),
  ('jk', 'Juscelino Kubitschek', '1902-09-12', 'Brasil', 'M', 'BR', 'XX', 'Política', 'Amendoim', array['juscelino', 'kubitschek', 'jk']::text[], '{}'::text[]),
  ('niemeyer', 'Oscar Niemeyer', '1907-12-15', 'Brasil', 'M', 'BR', 'XX', 'Arte', 'Gergelim', array['niemeyer']::text[], '{}'::text[]),
  ('senna', 'Ayrton Senna', '1960-03-21', 'Brasil', 'M', 'BR', 'XX', 'Esporte', 'Camarão', array['senna']::text[], '{}'::text[]),
  ('isabel', 'Princesa Isabel', '1846-07-29', 'Brasil', 'F', 'BR', 'XIX', 'Política', 'Leite', array['isabel']::text[], '{}'::text[]),
  ('bertha', 'Bertha Lutz', '1894-08-02', 'Brasil', 'F', 'BR', 'XIX', 'Ciência', 'Mel', array['bertha', 'lutz']::text[], '{}'::text[]),
  ('tarsila', 'Tarsila do Amaral', '1886-09-01', 'Brasil', 'F', 'BR', 'XIX', 'Arte', 'Morango', array['tarsila']::text[], '{}'::text[]),
  ('zilda', 'Zilda Arns', '1934-08-25', 'Brasil', 'F', 'BR', 'XX', 'Ciência', 'Penicilina', array['zilda']::text[], '{}'::text[]),
  ('esther', 'Maria Esther Bueno', '1939-10-11', 'Brasil', 'F', 'BR', 'XX', 'Esporte', 'Látex', array['maria esther', 'esther bueno']::text[], '{}'::text[]),
  ('elis', 'Elis Regina', '1945-03-17', 'Brasil', 'F', 'BR', 'XX', 'Arte', 'Kiwi', array['elis']::text[], '{}'::text[]),
  ('van-gogh', 'Vincent van Gogh', '1853-03-30', 'Holanda', 'M', 'EX', 'XIX', 'Arte', 'Tomate', array['van gogh', 'gogh']::text[], '{}'::text[]),
  ('gandhi', 'Mahatma Gandhi', '1869-10-02', 'Índia', 'M', 'EX', 'XIX', 'Política', 'Soja', array['gandhi']::text[], '{}'::text[]),
  ('einstein', 'Albert Einstein', '1879-03-14', 'Alemanha', 'M', 'EX', 'XIX', 'Ciência', 'Ovo', array['einstein']::text[], '{}'::text[]),
  ('turing', 'Alan Turing', '1912-06-23', 'Inglaterra', 'M', 'EX', 'XX', 'Ciência', 'Mostarda', array['turing']::text[], '{}'::text[]),
  ('mandela', 'Nelson Mandela', '1918-07-18', 'África do Sul', 'M', 'EX', 'XX', 'Política', 'Nozes', array['mandela']::text[], '{}'::text[]),
  ('ali', 'Muhammad Ali', '1942-01-17', 'EUA', 'M', 'EX', 'XX', 'Esporte', 'Picada de abelha', array['muhammad ali', 'cassius clay']::text[], array['abelha', 'picada']::text[]),
  ('curie', 'Marie Curie', '1867-11-07', 'Polônia', 'F', 'EX', 'XIX', 'Ciência', 'Poeira', array['curie']::text[], '{}'::text[]),
  ('chanel', 'Coco Chanel', '1883-08-19', 'França', 'F', 'EX', 'XIX', 'Arte', 'Chocolate', array['chanel']::text[], '{}'::text[]),
  ('earhart', 'Amelia Earhart', '1897-07-24', 'EUA', 'F', 'EX', 'XIX', 'Esporte', 'Pelo de gato', array['earhart', 'amelia']::text[], '{}'::text[]),
  ('frida', 'Frida Kahlo', '1907-07-06', 'México', 'F', 'EX', 'XX', 'Arte', 'Abacaxi', array['frida', 'kahlo']::text[], '{}'::text[]),
  ('rosa-parks', 'Rosa Parks', '1913-02-04', 'EUA', 'F', 'EX', 'XX', 'Política', 'Peixe', array['rosa parks', 'parks']::text[], '{}'::text[]),
  ('nadia', 'Nadia Comăneci', '1961-11-12', 'Romênia', 'F', 'EX', 'XX', 'Esporte', 'Glúten', array['nadia', 'comaneci']::text[], '{}'::text[])
on conflict (id) do update set
  name = excluded.name, birth = excluded.birth, country = excluded.country, gender = excluded.gender,
  origin = excluded.origin, century = excluded.century, area = excluded.area, weapon = excluded.weapon,
  aliases = excluded.aliases, weapon_aliases = excluded.weapon_aliases;
delete from game_private.characters where id not in ('machado', 'santos-dumont', 'getulio', 'jk', 'niemeyer', 'senna', 'isabel', 'bertha', 'tarsila', 'zilda', 'esther', 'elis', 'van-gogh', 'gandhi', 'einstein', 'turing', 'mandela', 'ali', 'curie', 'chanel', 'earhart', 'frida', 'rosa-parks', 'nadia');

insert into game_private.riddles (id, question, answers) values
  (1, 'O que é, o que é: tem dentes mas não morde?', array['pente']::text[]),
  (2, 'O que é, o que é: quanto mais se tira, maior fica?', array['buraco']::text[]),
  (3, 'O que é, o que é: tem cabeça e tem dente, não é bicho nem é gente?', array['alho']::text[]),
  (4, 'O que é, o que é: cai em pé e corre deitada?', array['chuva']::text[]),
  (5, 'O que é, o que é: tem pescoço mas não tem cabeça?', array['garrafa']::text[]),
  (6, 'O que é, o que é: tem coroa mas não é rei, tem escamas mas não é peixe?', array['abacaxi']::text[]),
  (7, 'O que é, o que é: quanto mais seca, mais molhada fica?', array['toalha']::text[]),
  (8, 'O que é, o que é: tem um olho só e não enxerga?', array['agulha']::text[]),
  (9, 'O que é, o que é: tem ponteiros mas não aponta para ninguém?', array['relógio']::text[]),
  (10, 'O que é, o que é: tem degraus, você sobe e desce, mas ela não sai do lugar?', array['escada']::text[]),
  (11, 'O que é, o que é: tem asa mas não voa, tem bico mas não bica?', array['bule']::text[]),
  (12, 'O que é, o que é: tem chapéu mas não tem cabeça, nasce na mata úmida?', array['cogumelo']::text[]),
  (13, 'O que é, o que é: nasce grande e morre pequeno de tanto escrever?', array['lápis']::text[]),
  (14, 'O que é, o que é: quanto mais cresce, menos se vê?', array['escuridão']::text[]),
  (15, 'O que é, o que é: passa na frente do sol e não faz sombra?', array['vento']::text[]),
  (16, 'O que é, o que é: tem folhas mas não é árvore, tem capa mas não é herói?', array['livro']::text[]),
  (17, 'O que é, o que é: tem cidades mas não tem casas, tem rios mas não tem água?', array['mapa']::text[]),
  (18, 'O que é, o que é: te segue o dia todo e some quando apagam a luz?', array['sombra']::text[]),
  (19, 'O que é, o que é: fica cheio de dia e vazio de noite, e anda sempre em par?', array['sapato', 'sapatos']::text[]),
  (20, 'O que é, o que é: quanto mais quente, mais fresco é?', array['pão']::text[]),
  (21, 'O que é, o que é: corre mas não tem pernas, tem leito mas não dorme?', array['rio']::text[]),
  (22, 'O que é, o que é: cai da árvore no outono sem se machucar?', array['folha']::text[]),
  (23, 'O que é, o que é: sempre está chegando mas nunca chega?', array['amanhã']::text[]),
  (24, 'O que é, o que é: é seu, mas os outros usam mais do que você?', array['nome']::text[]),
  (25, 'O que é, o que é: tem barba, tem cabelo, e dá pipoca?', array['milho']::text[]),
  (26, 'O que é, o que é: basta dizer o nome dele para quebrá-lo?', array['silêncio']::text[]),
  (27, 'O que é, o que é: tem rabo mas não é bicho, voa mas não é pássaro?', array['pipa', 'papagaio', 'pandorga']::text[]),
  (28, 'O que é, o que é: tem quatro pernas mas não anda, e ninguém senta nela para comer?', array['mesa']::text[]),
  (29, 'O que é, o que é: quanto mais se lava, mais suja fica?', array['água']::text[]),
  (30, 'O que é, o que é: tem teclas mas não abre fechadura?', array['teclado', 'piano']::text[]),
  (31, 'O que é, o que é: abre quando a chuva cai e fecha quando ela passa?', array['guarda-chuva', 'sombrinha']::text[]),
  (32, 'O que é, o que é: se põe na mesa, se parte, se reparte, mas não se come?', array['baralho']::text[]),
  (33, 'O que é, o que é: só aparece de noite e pisca lá no alto?', array['estrela']::text[]),
  (34, 'O que é, o que é: tem casco, anda devagar e vive muitos anos?', array['tartaruga']::text[]),
  (35, 'O que é, o que é: quanto mais você anda, mais deixa para trás?', array['pegadas', 'pegada']::text[]),
  (36, 'O que é, o que é: é cheia de buracos mas segura água?', array['esponja']::text[]),
  (37, 'O que é, o que é: vai e vem no parquinho sem sair do lugar?', array['balanço']::text[]),
  (38, 'O que é, o que é: tem uma perna só e dança sem parar?', array['pião']::text[]),
  (39, 'O que é, o que é: tem cabelo por fora, água por dentro e cai do coqueiro?', array['coco']::text[]),
  (40, 'O que é, o que é: quanto mais se enche, mais leve fica e sobe?', array['balão']::text[]),
  (41, 'O que é, o que é: tem cara e coroa mas não é rei?', array['moeda']::text[]),
  (42, 'O que é, o que é: tem asas de metal e leva gente pelo céu?', array['avião']::text[]),
  (43, 'O que é, o que é: anda com a casa nas costas e deixa um rastro brilhante?', array['caracol', 'lesma']::text[]),
  (44, 'O que é, o que é: é feito de água, mas se colocar na água ele some?', array['gelo']::text[]),
  (45, 'O que é, o que é: dá a volta no pasto inteiro sem sair do lugar?', array['cerca']::text[]),
  (46, 'O que é, o que é: come tudo que lhe dão, mas se beber água morre?', array['fogo']::text[]),
  (47, 'O que é, o que é: tem pés e cabeceira, mas não anda nem pensa?', array['cama']::text[]),
  (48, 'O que é, o que é: passa a vida na casa (da camisa) e mesmo assim fica do lado de fora?', array['botão']::text[]),
  (49, 'O que é, o que é: voa sem asas e chora sem olhos?', array['nuvem']::text[]),
  (50, 'O que é, o que é: é verde, fala, mas não é gente?', array['papagaio']::text[]),
  (51, 'O que é, o que é: tem cabeça, não pensa, e vive levando martelada?', array['prego']::text[]),
  (52, 'O que é, o que é: risca o céu na tempestade e ninguém consegue apagar?', array['relâmpago', 'raio']::text[]),
  (53, 'O que é, o que é: pequeno como um rato, guarda a casa como um leão?', array['cadeado']::text[]),
  (54, 'O que é, o que é: quanto mais você corre em cima dela, menos sai do lugar?', array['esteira']::text[]),
  (55, 'O que é, o que é: tem listras amarelas, zumbe e faz mel?', array['abelha']::text[]),
  (56, 'O que é, o que é: anda de quatro de manhã, com dois pés à tarde e com três à noite?', array['homem', 'ser humano', 'pessoa']::text[]),
  (57, 'O que é, o que é: cai do céu branquinho e derrete na mão?', array['neve']::text[]),
  (58, 'O que é, o que é: tem bolsa na barriga e pula pela Austrália?', array['canguru']::text[]),
  (59, 'O que é, o que é: parece um cavalo de pijama listrado?', array['zebra']::text[]),
  (60, 'O que é, o que é: tem tromba mas não é elefante, voa e pica?', array['mosquito', 'pernilongo']::text[]),
  (61, 'O que é, o que é: tem luz mas não é lâmpada, e pisca voando à noite?', array['vaga-lume', 'vagalume', 'pirilampo']::text[]),
  (62, 'O que é, o que é: só pode ser usado depois de quebrado?', array['ovo']::text[]),
  (63, 'O que é, o que é: tem dentes, não mastiga, e fecha a jaqueta?', array['zíper', 'fecho']::text[]),
  (64, 'O que é, o que é: grita no céu sem ter boca?', array['trovão']::text[]),
  (65, 'O que é, o que é: tem páginas, sai todo dia e fica velho no dia seguinte?', array['jornal']::text[]),
  (66, 'O que é, o que é: mora no mar e tem oito braços?', array['polvo']::text[]),
  (67, 'O que é, o que é: é gelado, doce, vem na casquinha e derrete no sol?', array['sorvete']::text[]),
  (68, 'O que é, o que é: anda de lado e tem duas pinças?', array['caranguejo', 'siri']::text[]),
  (69, 'O que é, o que é: tem vagões, anda sobre trilhos e apita?', array['trem']::text[]),
  (70, 'O que é, o que é: tem duas rodas, pedais e guidão?', array['bicicleta']::text[]),
  (71, 'O que é, o que é: mostra tudo o que você faz, mas não conta para ninguém?', array['espelho']::text[]),
  (72, 'O que é, o que é: acorda todo mundo cedo e canta no quintal?', array['galo']::text[]),
  (73, 'O que é, o que é: é redonda, todos chutam e ela vai para o gol?', array['bola']::text[]),
  (74, 'O que é, o que é: gira, gira, e deixa o quarto fresquinho?', array['ventilador']::text[]),
  (75, 'O que é, o que é: sai dos olhos quando a gente chora?', array['lágrima']::text[]),
  (76, 'O que é, o que é: dorme de cabeça para baixo e voa à noite?', array['morcego']::text[]),
  (77, 'O que é, o que é: come papel, casca e resto, e nunca fica satisfeita?', array['lixeira', 'lixo']::text[]),
  (78, 'O que é, o que é: tem sete cores e aparece depois da chuva?', array['arco-íris']::text[]),
  (79, 'O que é, o que é: troca de pele e anda rastejando?', array['cobra', 'serpente']::text[]),
  (80, 'O que é, o que é: tem espinhos, vive no deserto e guarda água?', array['cacto']::text[]),
  (81, 'O que é, o que é: vive na parede e caça mosquito?', array['lagartixa']::text[]),
  (82, 'O que é, o que é: tem doze meses e você pendura na parede?', array['calendário']::text[]),
  (83, 'O que é, o que é: tem teclas, tela e cabe no bolso?', array['celular', 'telefone']::text[]),
  (84, 'O que é, o que é: tem casca, gomos e vira suco de manhã?', array['laranja']::text[]),
  (85, 'O que é, o que é: tem tronco mas não é gente, tem copa mas não é cozinha?', array['árvore']::text[]),
  (86, 'O que é, o que é: quando fica velha a gente troca, e ela ilumina o quarto?', array['lâmpada']::text[]),
  (87, 'O que é, o que é: tem ponte, tem pedal, e a gente toca com as mãos?', array['violão', 'piano']::text[]),
  (88, 'O que é, o que é: tem barriga, não come, e faz chá apitando?', array['chaleira']::text[]),
  (89, 'O que é, o que é: tem juba e é o rei da selva?', array['leão']::text[]),
  (90, 'O que é, o que é: é branco, a vaca dá e a gente põe no café?', array['leite']::text[]),
  (91, 'O que é, o que é: tem cabo, tem cerdas e limpa o chão?', array['vassoura']::text[]),
  (92, 'O que é, o que é: sobe e desce o prédio sem usar degraus?', array['elevador']::text[])
on conflict (id) do update set question = excluded.question, answers = excluded.answers;

insert into game_private.quiz (id, question, options, answer) values
  (1, 'Qual é a capital do Brasil?', array['Brasília', 'Rio de Janeiro', 'São Paulo', 'Salvador']::text[], 0),
  (2, 'Quantos dias tem um ano bissexto?', array['365', '366', '364', '360']::text[], 1),
  (3, 'Qual planeta é conhecido como Planeta Vermelho?', array['Vênus', 'Júpiter', 'Marte', 'Saturno']::text[], 2),
  (4, 'Qual é o maior oceano do mundo?', array['Atlântico', 'Índico', 'Ártico', 'Pacífico']::text[], 3),
  (5, 'Quantas patas tem uma aranha?', array['8', '6', '10', '12']::text[], 0),
  (6, 'Qual é o maior mamífero do planeta?', array['Elefante-africano', 'Baleia-azul', 'Girafa', 'Tubarão-baleia']::text[], 1),
  (7, 'Em que continente fica o Egito?', array['Ásia', 'Europa', 'África', 'Oceania']::text[], 2),
  (8, 'Quanto é 7 × 8?', array['54', '64', '48', '56']::text[], 3),
  (9, 'Qual é o símbolo químico da água?', array['H₂O', 'CO₂', 'O₂', 'NaCl']::text[], 0),
  (10, 'Quem pintou a Mona Lisa?', array['Michelangelo', 'Leonardo da Vinci', 'Rafael', 'Van Gogh']::text[], 1),
  (11, 'Qual é a língua oficial do Brasil?', array['Espanhol', 'Inglês', 'Português', 'Tupi']::text[], 2),
  (12, 'Quantos minutos tem uma hora?', array['100', '30', '90', '60']::text[], 3),
  (13, 'Qual é o rio mais extenso do Brasil em volume de água?', array['Amazonas', 'São Francisco', 'Paraná', 'Tietê']::text[], 0),
  (14, 'Qual animal é conhecido como rei da selva?', array['Tigre', 'Leão', 'Elefante', 'Gorila']::text[], 1),
  (15, 'Quantos lados tem um hexágono?', array['5', '7', '6', '8']::text[], 2),
  (16, 'Qual é a cor resultante da mistura de azul e amarelo?', array['Roxo', 'Laranja', 'Marrom', 'Verde']::text[], 3),
  (17, 'Em que ano o Brasil foi descoberto pelos portugueses?', array['1500', '1492', '1822', '1600']::text[], 0),
  (18, 'Qual é o menor país do mundo?', array['Mônaco', 'Vaticano', 'Malta', 'San Marino']::text[], 1),
  (19, 'Qual gás as plantas absorvem na fotossíntese?', array['Oxigênio', 'Nitrogênio', 'Gás carbônico', 'Hélio']::text[], 2),
  (20, 'Quantos jogadores um time de futebol tem em campo?', array['10', '12', '9', '11']::text[], 3),
  (21, 'Qual é a capital da Argentina?', array['Buenos Aires', 'Santiago', 'Montevidéu', 'Lima']::text[], 0),
  (22, 'Qual é o maior país da América do Sul?', array['Argentina', 'Brasil', 'Peru', 'Colômbia']::text[], 1),
  (23, 'Qual instrumento tem teclas brancas e pretas?', array['Violão', 'Flauta', 'Piano', 'Bateria']::text[], 2),
  (24, 'Quantos estados tem o Brasil?', array['27', '25', '24', '26']::text[], 3),
  (25, 'Qual é o metal mais usado em fios elétricos?', array['Cobre', 'Ouro', 'Ferro', 'Chumbo']::text[], 0),
  (26, 'Qual é o satélite natural da Terra?', array['Sol', 'Lua', 'Marte', 'Europa']::text[], 1),
  (27, 'Quantos ossos tem o corpo humano adulto (aproximadamente)?', array['150', '300', '206', '98']::text[], 2),
  (28, 'Qual é o maior deserto quente do mundo?', array['Atacama', 'Gobi', 'Kalahari', 'Saara']::text[], 3),
  (29, 'Quem escreveu "Dom Casmurro"?', array['Machado de Assis', 'José de Alencar', 'Clarice Lispector', 'Jorge Amado']::text[], 0),
  (30, 'Qual é a moeda do Japão?', array['Yuan', 'Iene', 'Won', 'Rupia']::text[], 1),
  (31, 'Qual é o órgão responsável por bombear o sangue?', array['Pulmão', 'Fígado', 'Coração', 'Rim']::text[], 2),
  (32, 'Qual é o ponto mais alto do mundo?', array['Aconcágua', 'K2', 'Kilimanjaro', 'Monte Everest']::text[], 3),
  (33, 'Quantas cores tem o arco-íris?', array['7', '6', '5', '8']::text[], 0),
  (34, 'Qual é a capital da França?', array['Londres', 'Paris', 'Roma', 'Madri']::text[], 1),
  (35, 'Qual animal põe ovos e é mamífero?', array['Morcego', 'Golfinho', 'Ornitorrinco', 'Canguru']::text[], 2),
  (36, 'Qual é o maior planeta do Sistema Solar?', array['Saturno', 'Netuno', 'Terra', 'Júpiter']::text[], 3),
  (37, 'Em que país ficam as pirâmides de Gizé?', array['Egito', 'México', 'Peru', 'Sudão']::text[], 0),
  (38, 'Quanto é a metade de 150?', array['70', '75', '80', '65']::text[], 1),
  (39, 'Qual é o esporte de Ayrton Senna?', array['Tênis', 'Futebol', 'Fórmula 1', 'Vôlei']::text[], 2),
  (40, 'Qual é o estado mais populoso do Brasil?', array['Minas Gerais', 'Rio de Janeiro', 'Bahia', 'São Paulo']::text[], 3),
  (41, 'Qual é o idioma mais falado na Argentina?', array['Espanhol', 'Português', 'Inglês', 'Italiano']::text[], 0),
  (42, 'Qual é a estação do ano mais fria?', array['Outono', 'Inverno', 'Primavera', 'Verão']::text[], 1),
  (43, 'Quantas horas tem um dia?', array['12', '48', '24', '20']::text[], 2),
  (44, 'Qual inseto produz mel?', array['Formiga', 'Vespa', 'Borboleta', 'Abelha']::text[], 3),
  (45, 'Qual é o nome do nosso planeta?', array['Terra', 'Marte', 'Vênus', 'Mercúrio']::text[], 0),
  (46, 'Qual é a capital da Itália?', array['Milão', 'Roma', 'Veneza', 'Nápoles']::text[], 1),
  (47, 'Qual fruta é conhecida por ter a semente do lado de fora?', array['Manga', 'Abacate', 'Caju', 'Pêssego']::text[], 2),
  (48, 'Qual é o símbolo químico do ouro?', array['Ag', 'Fe', 'Go', 'Au']::text[], 3),
  (49, 'Qual é o maior bioma do Brasil?', array['Amazônia', 'Cerrado', 'Caatinga', 'Pampa']::text[], 0),
  (50, 'Quem foi o primeiro homem a pisar na Lua?', array['Yuri Gagarin', 'Neil Armstrong', 'Buzz Aldrin', 'Santos Dumont']::text[], 1),
  (51, 'Qual é o resultado de 12 ÷ 3?', array['3', '6', '4', '9']::text[], 2),
  (52, 'Qual é a capital de Portugal?', array['Porto', 'Coimbra', 'Braga', 'Lisboa']::text[], 3),
  (53, 'Qual é o maior osso do corpo humano?', array['Fêmur', 'Tíbia', 'Úmero', 'Crânio']::text[], 0),
  (54, 'Quantos meses tem um ano?', array['10', '12', '11', '13']::text[], 1),
  (55, 'Qual é a festa brasileira famosa pelos desfiles de escolas de samba?', array['Festa Junina', 'Réveillon', 'Carnaval', 'Páscoa']::text[], 2),
  (56, 'Qual gás respiramos para viver?', array['Hidrogênio', 'Gás carbônico', 'Metano', 'Oxigênio']::text[], 3),
  (57, 'Qual é o animal mais rápido em terra?', array['Guepardo', 'Leão', 'Cavalo', 'Avestruz']::text[], 0),
  (58, 'Qual cidade é conhecida como Cidade Maravilhosa?', array['Salvador', 'Rio de Janeiro', 'Recife', 'Florianópolis']::text[], 1),
  (59, 'Quantos segundos tem um minuto?', array['100', '30', '60', '120']::text[], 2),
  (60, 'Qual é o principal ingrediente do guacamole?', array['Tomate', 'Pepino', 'Milho', 'Abacate']::text[], 3),
  (61, 'Qual é o país do tango?', array['Argentina', 'Espanha', 'Cuba', 'México']::text[], 0),
  (62, 'Qual é o nome da estrela mais próxima da Terra?', array['Sírius', 'Sol', 'Alfa Centauri', 'Polar']::text[], 1),
  (63, 'Qual é o plural de "cidadão"?', array['Cidadões', 'Cidadães', 'Cidadãos', 'Cidadãs']::text[], 2),
  (64, 'Qual destes é um número primo?', array['15', '21', '27', '13']::text[], 3),
  (65, 'Qual é a capital da Espanha?', array['Madri', 'Barcelona', 'Sevilha', 'Valência']::text[], 0),
  (66, 'Qual é o maior felino do mundo?', array['Leão', 'Tigre', 'Onça-pintada', 'Leopardo']::text[], 1),
  (67, 'Qual vitamina o corpo produz com a luz do sol?', array['Vitamina C', 'Vitamina A', 'Vitamina D', 'Vitamina B12']::text[], 2),
  (68, 'Qual é o estado brasileiro conhecido pelo chimarrão?', array['Bahia', 'Pará', 'Goiás', 'Rio Grande do Sul']::text[], 3),
  (69, 'Quantas faces tem um cubo?', array['6', '4', '8', '12']::text[], 0),
  (70, 'Qual é a capital da Alemanha?', array['Munique', 'Berlim', 'Hamburgo', 'Frankfurt']::text[], 1),
  (71, 'Qual é o nome do processo de a água virar vapor?', array['Condensação', 'Solidificação', 'Evaporação', 'Fusão']::text[], 2),
  (72, 'Qual destes animais é um anfíbio?', array['Lagarto', 'Cobra', 'Tartaruga', 'Sapo']::text[], 3),
  (73, 'Qual é o país mais populoso da América do Sul?', array['Brasil', 'Colômbia', 'Argentina', 'Venezuela']::text[], 0),
  (74, 'Qual é a capital do Japão?', array['Osaka', 'Tóquio', 'Kyoto', 'Pequim']::text[], 1),
  (75, 'Quanto é 15 + 27?', array['41', '43', '42', '32']::text[], 2),
  (76, 'Qual é o maior órgão do corpo humano?', array['Fígado', 'Cérebro', 'Intestino', 'Pele']::text[], 3),
  (77, 'Em que cidade fica o Cristo Redentor?', array['Rio de Janeiro', 'São Paulo', 'Belo Horizonte', 'Brasília']::text[], 0),
  (78, 'Qual é a cor da clorofila?', array['Amarela', 'Verde', 'Vermelha', 'Azul']::text[], 1),
  (79, 'Quantos anos tem uma década?', array['100', '5', '10', '12']::text[], 2),
  (80, 'Qual é o autor de "Romeu e Julieta"?', array['Charles Dickens', 'Victor Hugo', 'Miguel de Cervantes', 'William Shakespeare']::text[], 3),
  (81, 'Qual é a capital do Canadá?', array['Ottawa', 'Toronto', 'Vancouver', 'Montreal']::text[], 0),
  (82, 'Qual destes é um mamífero marinho?', array['Tubarão', 'Golfinho', 'Atum', 'Polvo']::text[], 1)
on conflict (id) do update set question = excluded.question, options = excluded.options, answer = excluded.answer;
delete from game_private.quiz where id > 82;
