-- Arquivo gerado por scripts/generate-seed.ts — não edite à mão.
insert into game_private.riddles (id, question, answers) values
  (1, 'O que é, o que é: tem dentes mas não morde?', array['pente']::text[]),
  (2, 'O que é, o que é: quanto mais se tira, maior fica?', array['buraco']::text[]),
  (3, 'O que é, o que é: tem cabeça e tem dente, não é bicho nem é gente?', array['alho']::text[]),
  (4, 'O que é, o que é: cai em pé e corre deitada?', array['chuva']::text[]),
  (5, 'O que é, o que é: tem pescoço mas não tem cabeça?', array['garrafa']::text[]),
  (6, 'O que é, o que é: tem coroa mas não é rei, tem escamas mas não é peixe?', array['abacaxi']::text[]),
  (7, 'O que é, o que é: quanto mais seca, mais molhada fica?', array['toalha']::text[]),
  (8, 'O que é, o que é: tem um olho só e não enxerga?', array['agulha']::text[]),
  (9, 'O que é, o que é: tem ponteiros mas não aponta para ninguém?', array['relógio']::text[]),
  (10, 'O que é, o que é: tem degraus, você sobe e desce, mas ela não sai do lugar?', array['escada']::text[]),
  (11, 'O que é, o que é: tem asa mas não voa, tem bico mas não bica?', array['bule']::text[]),
  (12, 'O que é, o que é: tem chapéu mas não tem cabeça, nasce na mata úmida?', array['cogumelo']::text[]),
  (13, 'O que é, o que é: nasce grande e morre pequeno de tanto escrever?', array['lápis']::text[]),
  (14, 'O que é, o que é: quanto mais cresce, menos se vê?', array['escuridão']::text[]),
  (15, 'O que é, o que é: passa na frente do sol e não faz sombra?', array['vento']::text[]),
  (16, 'O que é, o que é: tem folhas mas não é árvore, tem capa mas não é herói?', array['livro']::text[]),
  (17, 'O que é, o que é: tem cidades mas não tem casas, tem rios mas não tem água?', array['mapa']::text[]),
  (18, 'O que é, o que é: te segue o dia todo e some quando apagam a luz?', array['sombra']::text[]),
  (19, 'O que é, o que é: fica cheio de dia e vazio de noite, e anda sempre em par?', array['sapato', 'sapatos']::text[]),
  (20, 'O que é, o que é: quanto mais quente, mais fresco é?', array['pão']::text[]),
  (21, 'O que é, o que é: corre mas não tem pernas, tem leito mas não dorme?', array['rio']::text[]),
  (22, 'O que é, o que é: cai da árvore no outono sem se machucar?', array['folha']::text[]),
  (23, 'O que é, o que é: sempre está chegando mas nunca chega?', array['amanhã']::text[]),
  (24, 'O que é, o que é: é seu, mas os outros usam mais do que você?', array['nome']::text[]),
  (25, 'O que é, o que é: tem barba, tem cabelo, e dá pipoca?', array['milho']::text[]),
  (26, 'O que é, o que é: basta dizer o nome dele para quebrá-lo?', array['silêncio']::text[]),
  (27, 'O que é, o que é: tem rabo mas não é bicho, voa mas não é pássaro?', array['pipa', 'papagaio', 'pandorga']::text[]),
  (28, 'O que é, o que é: tem quatro pernas mas não anda, e ninguém senta nela para comer?', array['mesa']::text[]),
  (29, 'O que é, o que é: quanto mais se lava, mais suja fica?', array['água']::text[]),
  (30, 'O que é, o que é: tem teclas mas não abre fechadura?', array['teclado', 'piano']::text[]),
  (31, 'O que é, o que é: abre quando a chuva cai e fecha quando ela passa?', array['guarda-chuva', 'sombrinha']::text[]),
  (32, 'O que é, o que é: se põe na mesa, se parte, se reparte, mas não se come?', array['baralho']::text[]),
  (33, 'O que é, o que é: só aparece de noite e pisca lá no alto?', array['estrela']::text[]),
  (34, 'O que é, o que é: tem casco, anda devagar e vive muitos anos?', array['tartaruga']::text[]),
  (35, 'O que é, o que é: quanto mais você anda, mais deixa para trás?', array['pegadas', 'pegada']::text[]),
  (36, 'O que é, o que é: é cheia de buracos mas segura água?', array['esponja']::text[]),
  (37, 'O que é, o que é: vai e vem no parquinho sem sair do lugar?', array['balanço']::text[]),
  (38, 'O que é, o que é: tem uma perna só e dança sem parar?', array['pião']::text[]),
  (39, 'O que é, o que é: tem cabelo por fora, água por dentro e cai do coqueiro?', array['coco']::text[]),
  (40, 'O que é, o que é: quanto mais se enche, mais leve fica e sobe?', array['balão']::text[]),
  (41, 'O que é, o que é: tem cara e coroa mas não é rei?', array['moeda']::text[]),
  (42, 'O que é, o que é: tem asas de metal e leva gente pelo céu?', array['avião']::text[]),
  (43, 'O que é, o que é: anda com a casa nas costas e deixa um rastro brilhante?', array['caracol', 'lesma']::text[]),
  (44, 'O que é, o que é: é feito de água, mas se colocar na água ele some?', array['gelo']::text[]),
  (45, 'O que é, o que é: dá a volta no pasto inteiro sem sair do lugar?', array['cerca']::text[]),
  (46, 'O que é, o que é: come tudo que lhe dão, mas se beber água morre?', array['fogo']::text[]),
  (47, 'O que é, o que é: tem pés e cabeceira, mas não anda nem pensa?', array['cama']::text[]),
  (48, 'O que é, o que é: passa a vida na casa (da camisa) e mesmo assim fica do lado de fora?', array['botão']::text[]),
  (49, 'O que é, o que é: voa sem asas e chora sem olhos?', array['nuvem']::text[]),
  (50, 'O que é, o que é: é verde, fala, mas não é gente?', array['papagaio']::text[]),
  (51, 'O que é, o que é: tem cabeça, não pensa, e vive levando martelada?', array['prego']::text[]),
  (52, 'O que é, o que é: risca o céu na tempestade e ninguém consegue apagar?', array['relâmpago', 'raio']::text[]),
  (53, 'O que é, o que é: pequeno como um rato, guarda a casa como um leão?', array['cadeado']::text[]),
  (54, 'O que é, o que é: quanto mais você corre em cima dela, menos sai do lugar?', array['esteira']::text[]),
  (55, 'O que é, o que é: tem listras amarelas, zumbe e faz mel?', array['abelha']::text[]),
  (56, 'O que é, o que é: anda de quatro de manhã, com dois pés à tarde e com três à noite?', array['homem', 'ser humano', 'pessoa']::text[]),
  (57, 'O que é, o que é: cai do céu branquinho e derrete na mão?', array['neve']::text[]),
  (58, 'O que é, o que é: tem bolsa na barriga e pula pela Austrália?', array['canguru']::text[]),
  (59, 'O que é, o que é: parece um cavalo de pijama listrado?', array['zebra']::text[]),
  (60, 'O que é, o que é: tem tromba mas não é elefante, voa e pica?', array['mosquito', 'pernilongo']::text[]),
  (61, 'O que é, o que é: tem luz mas não é lâmpada, e pisca voando à noite?', array['vaga-lume', 'vagalume', 'pirilampo']::text[]),
  (62, 'O que é, o que é: só pode ser usado depois de quebrado?', array['ovo']::text[]),
  (63, 'O que é, o que é: tem dentes, não mastiga, e fecha a jaqueta?', array['zíper', 'fecho']::text[]),
  (64, 'O que é, o que é: grita no céu sem ter boca?', array['trovão']::text[]),
  (65, 'O que é, o que é: tem páginas, sai todo dia e fica velho no dia seguinte?', array['jornal']::text[]),
  (66, 'O que é, o que é: mora no mar e tem oito braços?', array['polvo']::text[]),
  (67, 'O que é, o que é: é gelado, doce, vem na casquinha e derrete no sol?', array['sorvete']::text[]),
  (68, 'O que é, o que é: anda de lado e tem duas pinças?', array['caranguejo', 'siri']::text[]),
  (69, 'O que é, o que é: tem vagões, anda sobre trilhos e apita?', array['trem']::text[]),
  (70, 'O que é, o que é: tem duas rodas, pedais e guidão?', array['bicicleta']::text[]),
  (71, 'O que é, o que é: mostra tudo o que você faz, mas não conta para ninguém?', array['espelho']::text[]),
  (72, 'O que é, o que é: acorda todo mundo cedo e canta no quintal?', array['galo']::text[]),
  (73, 'O que é, o que é: é redonda, todos chutam e ela vai para o gol?', array['bola']::text[]),
  (74, 'O que é, o que é: gira, gira, e deixa o quarto fresquinho?', array['ventilador']::text[]),
  (75, 'O que é, o que é: sai dos olhos quando a gente chora?', array['lágrima']::text[]),
  (76, 'O que é, o que é: dorme de cabeça para baixo e voa à noite?', array['morcego']::text[]),
  (77, 'O que é, o que é: come papel, casca e resto, e nunca fica satisfeita?', array['lixeira', 'lixo']::text[]),
  (78, 'O que é, o que é: tem sete cores e aparece depois da chuva?', array['arco-íris']::text[]),
  (79, 'O que é, o que é: troca de pele e anda rastejando?', array['cobra', 'serpente']::text[]),
  (80, 'O que é, o que é: tem espinhos, vive no deserto e guarda água?', array['cacto']::text[]),
  (81, 'O que é, o que é: vive na parede e caça mosquito?', array['lagartixa']::text[]),
  (82, 'O que é, o que é: tem doze meses e você pendura na parede?', array['calendário']::text[]),
  (83, 'O que é, o que é: tem teclas, tela e cabe no bolso?', array['celular', 'telefone']::text[]),
  (84, 'O que é, o que é: tem casca, gomos e vira suco de manhã?', array['laranja']::text[]),
  (85, 'O que é, o que é: tem tronco mas não é gente, tem copa mas não é cozinha?', array['árvore']::text[]),
  (86, 'O que é, o que é: quando fica velha a gente troca, e ela ilumina o quarto?', array['lâmpada']::text[]),
  (87, 'O que é, o que é: tem ponte, tem pedal, e a gente toca com as mãos?', array['violão', 'piano']::text[]),
  (88, 'O que é, o que é: tem barriga, não come, e faz chá apitando?', array['chaleira']::text[]),
  (89, 'O que é, o que é: tem juba e é o rei da selva?', array['leão']::text[]),
  (90, 'O que é, o que é: é branco, a vaca dá e a gente põe no café?', array['leite']::text[]),
  (91, 'O que é, o que é: tem cabo, tem cerdas e limpa o chão?', array['vassoura']::text[]),
  (92, 'O que é, o que é: sobe e desce o prédio sem usar degraus?', array['elevador']::text[])
on conflict (id) do update set question = excluded.question, answers = excluded.answers;
